---
image: maven:3.3-jdk-8

#variables:
#  MAVEN_OPTS: >-
#    -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
#    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
#    -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
#
#  MAVEN_CLI_OPTS: >-
#    --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

stages:
  - test
  - build
  - docker

before_script:
  - which ssh-agent || ( apt-get install -qq openssh-client )
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  - echo -e "\tUser gitlab\n\n" >> ~/.ssh/config

test:verify:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify

build:vulcan4:
  stage: build
  only:
    - tags
    - master
  script:
    - mvn deploy

docker:trigger_build:
  image: curlimages/curl
  stage: docker
  only:
    - tags
    - master
  before_script:
    - echo skipping before script
  script:
    - >-
      curl
      -X POST
      --form token=${TRIGGER_TOKEN}
      --form ref=master
      --form variables[WINSTON_VERSION]=$CI_COMMIT_TAG
      https://code.chs.usgs.gov/api/v4/projects/4438/trigger/pipeline
